import Head from "next/head";
import LayoutDashboardThree from "@components/dashboardthree/LayoutDashboardThree";

export default function Index() {
  return (
    <>
      <Head>
        <title>Dashboard Three Column</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutDashboardThree>
        <div className="flex gap-x-4">

          <div className="w-full">
            <div id="first" className="bg-blue-500 h-screen mb-4 flex items-center justify-center">
              <h1 className="text-white font-medium text-2xl px-8">Example Dashboard Layout Three Column</h1>
            </div>
            <div id="second" className="bg-orange-500 h-screen my-4"></div>
            <div id="third" className="bg-violet-500 h-screen mt-4"></div>
          </div>

          <div className="hidden xl:block w-52 text-sm">
            <div className="sticky top-14">
              <h5 className="mb-3 text-sm font-semibold text-gray-900 dark:text-white">On This Page</h5>
              <nav>
                <ul className="flex flex-col gap-y-2">
                  <li className="font-medium text-neutral-600 hover:text-neutral-800 dark:text-gray-300 dark:hover:text-white transition-all">
                    <a href="#first">First</a>
                  </li>
                  <li className="font-medium text-neutral-600 hover:text-neutral-800 dark:text-gray-300 dark:hover:text-white transition-all">
                    <a href="#second">Second</a>
                  </li>
                  <li className="font-medium text-neutral-600 hover:text-neutral-800 dark:text-gray-300 dark:hover:text-white transition-all">
                    <a href="#third">Third</a>
                  </li>
                </ul>
              </nav>
            </div>
          </div>

        </div>
      </LayoutDashboardThree>
    </>
  )
}