import LayoutDashboard from "@components/dashboard/LayoutDashboard";
import { Fragment, useState, useContext } from 'react'
import { GlobalContext } from "@utils/GlobalContext";
import { Dialog, Transition, Menu } from '@headlessui/react'
import { ChevronRightIcon, MenuIcon, MoonIcon, SunIcon, XIcon } from '@heroicons/react/outline'
import Head from "next/head";
import ActiveLink from "@components/ActiveLink";
import Layout from "@components/Layout";
import SidebarMenu from "@components/dashboard/SidebarMenu";
import ThemeToggle from "@components/dashboard/ThemeToggle";
import DashboardNav from "@components/dashboard/DashboardNav";
import MobileMenu from "@components/dashboard/MobileMenu";
import Breadcrumb from "@components/Breadcrumb";

export default function Index() {

  const [openMobileMenu, setOpenMobileMenu] = useState(false)
  const { darkMode, setDarkMode } = useContext(GlobalContext);

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>

        <ThemeToggle />

        <DashboardNav />

        <MobileMenu />

        <div className="max-w-screen-2xl mx-auto px-2 mt-2 border dark:border-neutral-700 h-full">
          <div className="lg:flex py-2 h-full">

            <SidebarMenu />

            <main className="px-2 w-full border dark:border-neutral-700 lg:ml-60">

              <Breadcrumb />
              
              <div className="bg-red-500 h-96 flex items-center justify-center">
                <h1 className="text-white font-medium text-2xl px-8">{`The "First" Menu Accordion Should Be Opened`}</h1>
              </div>
              <div className="bg-teal-500 h-96">
              </div>
              <div className="bg-blue-500 h-96">
              </div>
            </main>
          </div>
        </div >

      </Layout>
    </>
  )
}