import Head from "next/head";
import LayoutDashboardTwo from "@components/dashboardtwo/LayoutDashboardTwo";

export default function Index() {
  return (
    <>
      <Head>
        <title>Dashboard Two</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutDashboardTwo>
        <div className="bg-green-500 h-96 flex items-center justify-center">
          <h1 className="text-white font-medium text-2xl px-8">Example Dashboard Layout Two Column</h1>
        </div>
        <div className="bg-violet-500 h-96">
        </div>
        <div className="bg-red-500 h-96">
        </div>
      </LayoutDashboardTwo>
    </>
  )
}