import { Fragment, useContext } from "react";
import Head from "next/head";
import { GlobalContext } from "@utils/GlobalContext";
import { Transition } from '@headlessui/react'
import Button from "@components/Button";
import ButtonOutline from "@components/ButtonOutline";
import ButtonPills from "@components/ButtonPills";
import ButtonOutlinePills from "@components/ButtonOutlinePills";
import Heading from "@components/Heading";
import Footer from "@components/Footer"
import Navbar from "@components/Navbar";
import Text from "@components/Text";
import Code from "@components/Code";
import Alert from "@components/Alert";
import AlertOutline from "@components/AlertOutline";
import Badge from "@components/Badge";
import BadgeOutline from "@components/BadgeOutline";
import BadgePills from "@components/BadgePills";
import BadgeOutlinePills from "@components/BadgeOutlinePills";
import Skeletons from "@components/Skeletons";
import { DownloadIcon, InformationCircleIcon, MoonIcon, PlusCircleIcon, SunIcon } from "@heroicons/react/outline";
import Section from "@components/Section";
import Container from "@components/Container";

export default function Third() {
	const { darkMode, setDarkMode } = useContext(GlobalContext);

	return (
		<div>
			<Head>
				<title>Components</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<main className="dark:bg-neutral-900">

				<Section id="dark-mode" name="Dark Mode" className="px-2 sm:px-6 md:px-12">
					<div className="flex gap-3 flex-wrap">
						<div
							onClick={() => setDarkMode(!darkMode)}
							className="transition-all cursor-pointer w-12 h-7 dark:bg-blue-500 bg-neutral-200 rounded-full relative"
						>
							<div className="h-5 w-5 bg-white rounded-full absolute top-1 transition-all duration-300 dark:left-6 left-1"></div>
						</div>
						<button onClick={() => setDarkMode(!darkMode)} className="relative flex items-center py-0.5 px-1 bg-blue-500 rounded-full h-7">
							<span className="absolute w-5 h-5 rounded-full bg-white dark:left-[1.7rem] left-1 transition-all duration-300"></span>
							<span aria-hidden={true}>☀️</span>
							<span aria-hidden={true}>🌙</span>
						</button>
						<button onClick={() => setDarkMode(!darkMode)} className={`${darkMode ? "bg-gray-800" : "bg-gray-200"} relative flex gap-1 items-center px-1 py-0.5 rounded-full h-7`}>
							<span className="absolute w-5 h-5 rounded-full bg-blue-500 dark:left-[1.6rem] left-1.5 transition-all duration-300"></span>
							<span aria-hidden={true}><SunIcon className={`${darkMode ? "text-white bg-white" : ""}h-5 w-5`} /></span>
							<span aria-hidden={true}><MoonIcon className="h-5 w-5" /></span>
						</button>
						{darkMode ?
							<button onClick={() => setDarkMode(!darkMode)} className="w-8 h-8 p-1 transition-all ease-in duration-300 bg-neutral-800 hover:bg-neutral-700 text-white rounded-full">
								<SunIcon />
							</button>
							:
							<button onClick={() => setDarkMode(!darkMode)} className="w-8 h-8 p-1 transition-all ease-in duration-300 bg-gray-100 hover:bg-gray-200 rounded-full">
								<MoonIcon className="transform rotate-45" />
							</button>
						}
					</div>
				</Section>

				<div className="!py-2 px-2 rounded my-10 mx-4 bg-opacity-20 dark:bg-opacity-40 bg-gray-100 dark:bg-neutral-800 backdrop-filter backdrop-blur fixed bottom-3 md:bottom-1/3 right-3 md:right-10 z-40">
					{darkMode ?
						<button onClick={() => setDarkMode(!darkMode)} className="w-8 h-8 p-1 transition-all ease-in duration-300 bg-neutral-800 hover:bg-neutral-700 text-white rounded-full">
							<SunIcon />
						</button>
						:
						<button onClick={() => setDarkMode(!darkMode)} className="w-8 h-8 p-1 transition-all ease-in duration-300 bg-gray-100 hover:bg-gray-200 rounded-full">
							<MoonIcon />
						</button>
					}
				</div>

				<Section id="section" name="Section" className="px-2 sm:px-6 md:px-12">
					<Section className="!py-0">
						<Text>Section Content no Title</Text>
					</Section>
					<Section id="sectiontitle" name="Section With Title" className="!py-0">
						<Text>Section Content</Text>
					</Section>
					<Code code={
						`import Section from "@components/Section";

<Section className="!py-0">
	<Text>Section Content no Title</Text>
</Section>
<Section id="sectiontitle" name="Section With Title" className="!py-0">
	<Text>Section Content</Text>
</Section>`
					}>
					</Code>
				</Section>

				<Section id="container" name="Container" className="px-2 sm:px-6 md:px-12">
					<Container>
						<Text>Container Default</Text>
					</Container>
					<Container small>
						<Text>Container Small</Text>
					</Container>
					<Code code={
						`import Container from "@components/Container";

<Container>
	<Text>Container Default</Text>
</Container>
<Container small>
	<Text>Container Small</Text>
</Container>`
					}>
					</Code>
				</Section>

				<Section id="heading" name="Heading" className="px-2 sm:px-6 md:px-12">
					<Heading>Heading Default</Heading>
					<Heading.h2>Heading 2</Heading.h2>
					<Heading.h3>Heading 3</Heading.h3>
					<Heading.h4>Heading 4</Heading.h4>
					<Heading.h5>Heading 5</Heading.h5>
					<Heading.h6>Heading 6</Heading.h6>
					<Code code={
						`import Heading from "@components/Heading";

<Heading>Heading Default</Heading>
<Heading.h2>Heading 2</Heading.h2>
<Heading.h3>Heading 3</Heading.h3>
<Heading.h4>Heading 4</Heading.h4>
<Heading.h5>Heading 5</Heading.h5>
<Heading.h6>Heading 6</Heading.h6>`
					}>
					</Code>
				</Section>

				<Section id="text" name="Text" className="px-2 sm:px-6 md:px-12">
					<Text.light className="mb-2">Text Light</Text.light>
					<Text className="mb-2">Text Normal</Text>
					<Text.medium>Text Medium</Text.medium>
					<Text.bold>Text Bold</Text.bold>
					<Text.extrabold>Text Extra Bold</Text.extrabold>
					<Code code={
						`import Text from "@components/Text";

<Text.light className="mb-2">Text Light</Text.light>
<Text className="mb-2">Text Normal</Text>
<Text.medium>Text Medium</Text.medium>
<Text.bold>Text Bold</Text.bold>
<Text.extrabold>Text Extra Bold</Text.extrabold>`
					}>
					</Code>
				</Section>

				<Section id="button" name="Button" className="px-2 sm:px-6 md:px-12">
					<div className="flex items-center flex-wrap gap-2">
						<Button className="flex gap-1 items-center"><PlusCircleIcon className="h-5 w-5" />Default</Button>
						<Button.green>Green</Button.green>
						<Button.yellow>Yellow</Button.yellow>
						<Button.orange>Orange</Button.orange>
						<Button.red>Red</Button.red>
						<Button.purple>Purple</Button.purple>
						<Button.dark>Dark</Button.dark>
					</div>
					<Code code={
						`import Button from "@components/Button";

<Button className="flex gap-1 items-center"><PlusCircleIcon className="h-5 w-5" />Default</Button>
<Button.green>Green</Button.green>
<Button.yellow>Yellow</Button.yellow>
<Button.orange>Orange</Button.orange>
<Button.red>Red</Button.red>
<Button.purple>Purple</Button.purple>
<Button.dark>Dark</Button.dark>`
					}>
					</Code>
				</Section>

				<Section id="button-outline" name="Button Outline" className="px-2 sm:px-6 md:px-12">
					<div className="flex items-center flex-wrap gap-2">
						<ButtonOutline className="flex gap-1 items-center"><DownloadIcon className="h-5 w-5" />Default</ButtonOutline>
						<ButtonOutline.green>Green</ButtonOutline.green>
						<ButtonOutline.yellow>Yellow</ButtonOutline.yellow>
						<ButtonOutline.orange>Orange</ButtonOutline.orange>
						<ButtonOutline.red>Red</ButtonOutline.red>
						<ButtonOutline.purple>Purple</ButtonOutline.purple>
						<ButtonOutline.dark>Dark</ButtonOutline.dark>
					</div>
					<Code code={
						`import ButtonOutline from "@components/ButtonOutline";

<ButtonOutline className="flex gap-1 items-center"><DownloadIcon className="h-5 w-5"/>Default</ButtonOutline>
<ButtonOutline.green>Green</ButtonOutline.green>
<ButtonOutline.yellow>Yellow</ButtonOutline.yellow>
<ButtonOutline.orange>Orange</ButtonOutline.orange>
<ButtonOutline.red>Red</ButtonOutline.red>
<ButtonOutline.purple>Purple</ButtonOutline.purple>
<ButtonOutline.dark>Dark</ButtonOutline.dark>`
					}>
					</Code>
				</Section>

				<Section id="button-pills" name="Button Pills" className="px-2 sm:px-6 md:px-12">
					<div className="flex items-center flex-wrap gap-2">
						<ButtonPills className="flex gap-1 items-center"><DownloadIcon className="h-5 w-5" />Default</ButtonPills>
						<ButtonPills.green>Green</ButtonPills.green>
						<ButtonPills.yellow>Yellow</ButtonPills.yellow>
						<ButtonPills.orange>Orange</ButtonPills.orange>
						<ButtonPills.red>Red</ButtonPills.red>
						<ButtonPills.purple>Purple</ButtonPills.purple>
						<ButtonPills.dark>Dark</ButtonPills.dark>
					</div>
					<Code code={
						`import ButtonPills from "@components/ButtonPills";

<ButtonPills className="flex gap-1 items-center"><DownloadIcon className="h-5 w-5"/>Default</ButtonPills>
<ButtonPills.green>Green</ButtonPills.green>
<ButtonPills.yellow>Yellow</ButtonPills.yellow>
<ButtonPills.orange>Orange</ButtonPills.orange>
<ButtonPills.red>Red</ButtonPills.red>
<ButtonPills.purple>Purple</ButtonPills.purple>
<ButtonPills.dark>Dark</ButtonPills.dark>`
					}>
					</Code>
				</Section>

				<Section id="button-outline-pills" name="Button Outline Pills" className="px-2 sm:px-6 md:px-12">
					<div className="flex items-center flex-wrap gap-2">
						<ButtonOutlinePills className="flex gap-1 items-center"><DownloadIcon className="h-5 w-5" />Default</ButtonOutlinePills>
						<ButtonOutlinePills.green>Green</ButtonOutlinePills.green>
						<ButtonOutlinePills.yellow>Yellow</ButtonOutlinePills.yellow>
						<ButtonOutlinePills.orange>Orange</ButtonOutlinePills.orange>
						<ButtonOutlinePills.red>Red</ButtonOutlinePills.red>
						<ButtonOutlinePills.purple>Purple</ButtonOutlinePills.purple>
						<ButtonOutlinePills.dark>Dark</ButtonOutlinePills.dark>
					</div>
					<Code code={
						`import ButtonOutlinePills from "@components/ButtonOutlinePills";

<ButtonOutlinePills className="flex gap-1 items-center"><DownloadIcon className="h-5 w-5" />Default</ButtonOutlinePills>
<ButtonOutlinePills.green>Green</ButtonOutlinePills.green>
<ButtonOutlinePills.yellow>Yellow</ButtonOutlinePills.yellow>
<ButtonOutlinePills.orange>Orange</ButtonOutlinePills.orange>
<ButtonOutlinePills.red>Red</ButtonOutlinePills.red>
<ButtonOutlinePills.purple>Purple</ButtonOutlinePills.purple>
<ButtonOutlinePills.dark>Dark</ButtonOutlinePills.dark>`
					}>
					</Code>
				</Section>

				<Section id="badge" name="Badge" className="px-2 sm:px-6 md:px-12">
					<div className="flex items-center flex-wrap gap-2">
						<Badge className="flex gap-1 items-center"><DownloadIcon className="h-4 w-4" />Default</Badge>
						<Badge.green>Green</Badge.green>
						<Badge.red isLarge>Red</Badge.red>
						<Badge.yellow isLarge>Yellow</Badge.yellow>
						<Badge.orange>Orange</Badge.orange>
						<Badge.purple>Purple</Badge.purple>
						<Badge.dark>Dark</Badge.dark>
					</div>
					<Code code={
						`import Badge from "@components/Badge";

<Badge className="flex gap-1 items-center"><DownloadIcon className="h-4 w-4" />Default</Badge>
<Badge.green>Green</Badge.green>
<Badge.red isLarge>Red</Badge.red>
<Badge.yellow isLarge>Yellow</Badge.yellow>
<Badge.orange>Orange</Badge.orange>
<Badge.purple>Purple</Badge.purple>
<Badge.dark>Dark</Badge.dark>`
					}>
					</Code>
				</Section>

				<Section id="badge-outline" name="Badge Outline" className="px-2 sm:px-6 md:px-12">
					<div className="flex items-center flex-wrap gap-2">
						<BadgeOutline className="flex gap-1 items-center"><DownloadIcon className="h-4 w-4" />Default</BadgeOutline>
						<BadgeOutline.green>Green</BadgeOutline.green>
						<BadgeOutline.red isLarge>Red</BadgeOutline.red>
						<BadgeOutline.yellow isLarge>Yellow</BadgeOutline.yellow>
						<BadgeOutline.orange>Orange</BadgeOutline.orange>
						<BadgeOutline.purple>Purple</BadgeOutline.purple>
						<BadgeOutline.dark>Dark</BadgeOutline.dark>
					</div>
					<Code code={
						`import BadgeOutline from "@components/BadgeOutline";

<BadgeOutline className="flex gap-1 items-center"><DownloadIcon className="h-4 w-4" />Default</BadgeOutline>
<BadgeOutline.green>Green</BadgeOutline.green>
<BadgeOutline.red isLarge>Red</BadgeOutline.red>
<BadgeOutline.yellow isLarge>Yellow</BadgeOutline.yellow>
<BadgeOutline.orange>Orange</BadgeOutline.orange>
<BadgeOutline.purple>Purple</BadgeOutline.purple>
<BadgeOutline.dark>Dark</BadgeOutline.dark>`
					}>
					</Code>
				</Section>

				<Section id="badge-pills" name="Badge Pills" className="px-2 sm:px-6 md:px-12">
					<div className="flex items-center flex-wrap gap-2">
						<BadgePills className="flex gap-1 items-center"><DownloadIcon className="h-4 w-4" />Default</BadgePills>
						<BadgePills.green>Green</BadgePills.green>
						<BadgePills.red isLarge>Red</BadgePills.red>
						<BadgePills.yellow isLarge>Yellow</BadgePills.yellow>
						<BadgePills.orange>Orange</BadgePills.orange>
						<BadgePills.purple>Purple</BadgePills.purple>
						<BadgePills.dark>Dark</BadgePills.dark>
					</div>
					<Code code={
						`import BadgePills from "@components/BadgePills";

<BadgePills className="flex gap-1 items-center"><DownloadIcon className="h-4 w-4" />Default</BadgePills>
<BadgePills.green>Green</BadgePills.green>
<BadgePills.red isLarge>Red</BadgePills.red>
<BadgePills.yellow isLarge>Yellow</BadgePills.yellow>
<BadgePills.orange>Orange</BadgePills.orange>
<BadgePills.purple>Purple</BadgePills.purple>
<BadgePills.dark>Dark</BadgePills.dark>`
					}>
					</Code>
				</Section>

				<Section id="badge-outline-pills" name="Badge Outline Pills" className="px-2 sm:px-6 md:px-12">
					<div className="flex items-center flex-wrap gap-2">
						<BadgeOutlinePills className="flex gap-1 items-center"><DownloadIcon className="h-4 w-4" />Default</BadgeOutlinePills>
						<BadgeOutlinePills.green>Green</BadgeOutlinePills.green>
						<BadgeOutlinePills.red isLarge>Red</BadgeOutlinePills.red>
						<BadgeOutlinePills.yellow isLarge>Yellow</BadgeOutlinePills.yellow>
						<BadgeOutlinePills.orange>Orange</BadgeOutlinePills.orange>
						<BadgeOutlinePills.purple>Purple</BadgeOutlinePills.purple>
						<BadgeOutlinePills.dark>Dark</BadgeOutlinePills.dark>
					</div>
					<Code code={
						`import BadgeOutlinePills from "@components/BadgeOutlinePills";

<BadgeOutlinePills className="flex gap-1 items-center"><DownloadIcon className="h-4 w-4" />Default</BadgeOutlinePills>
<BadgeOutlinePills.green>Green</BadgeOutlinePills.green>
<BadgeOutlinePills.red isLarge>Red</BadgeOutlinePills.red>
<BadgeOutlinePills.yellow isLarge>Yellow</BadgeOutlinePills.yellow>
<BadgeOutlinePills.orange>Orange</BadgeOutlinePills.orange>
<BadgeOutlinePills.purple>Purple</BadgeOutlinePills.purple>
<BadgeOutlinePills.dark>Dark</BadgeOutlinePills.dark>`
					}>
					</Code>
				</Section>

				<Section id="alert" name="Alert" className="px-2 sm:px-6 md:px-12">
					<Alert className="flex gap-1 items-center font-medium" isLarge><InformationCircleIcon className="h-5 w-5" />Default</Alert>
					<Alert.green>Green</Alert.green>
					<Alert.red className="flex gap-1 items-center font-medium" isLarge><InformationCircleIcon className="h-5 w-5" />Red <span className="font-normal">Danger</span></Alert.red>
					<Alert.yellow isLarge>Yellow</Alert.yellow>
					<Alert.orange>Orange</Alert.orange>
					<Alert.purple>Purple</Alert.purple>
					<Alert.dark>Dark</Alert.dark>
					<Code code={
						`import Alert from "@components/Alert";

<Alert className="flex gap-1 items-center font-medium" isLarge><InformationCircleIcon className="h-5 w-5"/>Default</Alert>
<Alert.green>Green</Alert.green>
<Alert.red className="flex gap-1 items-center font-medium" isLarge><InformationCircleIcon className="h-5 w-5" />Red <span className="font-normal">Danger</span></Alert.red>
<Alert.yellow isLarge>Yellow</Alert.yellow>
<Alert.orange>Orange</Alert.orange>
<Alert.purple>Purple</Alert.purple>
<Alert.dark>Dark</Alert.dark>`
					}>
					</Code>
				</Section>

				<Section id="alert-outline" name="Alert Outline" className="px-2 sm:px-6 md:px-12">
					<AlertOutline className="flex gap-1 items-center font-medium" isLarge><InformationCircleIcon className="h-5 w-5" />Default</AlertOutline>
					<AlertOutline.green>Green</AlertOutline.green>
					<AlertOutline.red className="flex gap-1 items-center font-medium" isLarge><InformationCircleIcon className="h-5 w-5" />Red <span className="font-normal">Danger</span></AlertOutline.red>
					<AlertOutline.yellow isLarge>Yellow</AlertOutline.yellow>
					<AlertOutline.orange>Orange</AlertOutline.orange>
					<AlertOutline.purple>Purple</AlertOutline.purple>
					<AlertOutline.dark>Dark</AlertOutline.dark>
					<Code code={
						`import AlertOutline from "@components/AlertOutline";

<AlertOutline className="flex gap-1 items-center font-medium" isLarge><InformationCircleIcon className="h-5 w-5" />Default</AlertOutline>
<AlertOutline.green>Green</AlertOutline.green>
<AlertOutline.red className="flex gap-1 items-center font-medium" isLarge><InformationCircleIcon className="h-5 w-5" />Red <span className="font-normal">Danger</span></AlertOutline.red>
<AlertOutline.yellow isLarge>Yellow</AlertOutline.yellow>
<AlertOutline.orange>Orange</AlertOutline.orange>
<AlertOutline.purple>Purple</AlertOutline.purple>
<AlertOutline.dark>Dark</AlertOutline.dark>`
					}>
					</Code>
				</Section>

				<Section id="skeletons" name="Skeletons" className="px-2 sm:px-6 md:px-12">
					<Skeletons className="!h-32 w-full" />
					<Skeletons className="max-w-[12rem]" />
					<Skeletons className="max-w-[24rem] !rounded-full" />
					<Skeletons className="!w-24 !h-24 !rounded-full" />
					<Code code={
						`import Skeletons from "@components/Skeletons";

<Skeletons className="!h-32 w-full" />
<Skeletons className="max-w-[12rem]" />
<Skeletons className="max-w-[24rem] !rounded-full" />
<Skeletons className="!w-24 !h-24 !rounded-full" />`
					}>
					</Code>
				</Section>

			</main>

			<Footer />

		</div>
	);
}