import Head from "next/head";
import Image from "next/image";
import Footer from "@components/Footer";
import Navbar from "@components/Navbar";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Home Page</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<main className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
				<section className="text-gray-600 body-font">
					<div className="mx-auto flex py-24 md:flex-row flex-col items-center">
						<div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
							<h1 className="sm:text-8xl text-3xl mb-4 font-bold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">
								Before they sold out
							</h1>
							<p className="mb-8 leading-relaxed">
								Copper mug try-hard pitchfork pour-over freegan
								heirloom neutra air plant cold-pressed tacos
								poke beard tote bag. Heirloom echo park mlkshk
								tote bag selvage hot chicken authentic tumeric
								truffaut hexagon try-hard chambray.
							</p>
							<div className="flex justify-center">
								<button className="inline-flex text-white bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-900 rounded text-lg">
									Button
								</button>
								<button className="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">
									Button
								</button>
							</div>
						</div>
						<div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
							<Image
								className="object-cover object-center rounded"
								src="https://dummyimage.com/720x600"
								alt="hero"
								width={500}
								height={500}
							/>
						</div>
					</div>
				</section>
				<h1 className="sm:text-4xl text-3xl my-4 font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-red-600">
					Gradient MonoChrome
				</h1>
				<button type="button" className="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Blue</button>
				<button type="button" className="text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Green</button>
				<button type="button" className="text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Cyan</button>
				<button type="button" className="text-white bg-gradient-to-r from-teal-400 via-teal-500 to-teal-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Teal</button>
				<button type="button" className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Lime</button>
				<button type="button" className="text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Red</button>
				<button type="button" className="text-white bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Pink</button>
				<button type="button" className="text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Purple</button>

				<h1 className="sm:text-4xl text-3xl my-4 font-bold text-transparent bg-clip-text bg-gradient-to-r from-red-400 to-yellow-600">
					Gradient DualTone
				</h1>
				<button type="button" className="text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Purple to Blue</button>
				<button type="button" className="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Cyan to Blue</button>
				<button type="button" className="text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Green to Blue</button>
				<button type="button" className="text-white bg-gradient-to-r from-purple-500 to-pink-500 hover:bg-gradient-to-l font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Purple to Pink</button>
				<button type="button" className="text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Pink to Orange</button>
				<button type="button" className="text-gray-900 bg-gradient-to-r from-teal-200 to-lime-200 hover:bg-gradient-to-l font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Teal to Lime</button>
				<button type="button" className="text-gray-900 bg-gradient-to-r from-red-200 to-yellow-200 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Red to Yellow</button>

				<h1 className="sm:text-4xl text-3xl my-4 font-bold text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-purple-600">
					Gradient Outline
				</h1>
				<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white">
					<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
						Purple to blue
					</span>
				</button>
				<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white">
					<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
						Cyan to blue
					</span>
				</button>
				<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-green-400 to-blue-600 group-hover:from-green-400 group-hover:to-blue-600 hover:text-white dark:text-white">
					<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
						Green to blue
					</span>
				</button>
				<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-500 to-pink-500 group-hover:from-purple-500 group-hover:to-pink-500 hover:text-white dark:text-white">
					<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
						Purple to pink
					</span>
				</button>
				<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-pink-500 to-orange-400 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white">
					<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
						Pink to orange
					</span>
				</button>
				<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-teal-300 to-lime-300 group-hover:from-teal-300 group-hover:to-lime-300 dark:text-white dark:hover:text-gray-900">
					<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
						Teal to Lime
					</span>
				</button>
				<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-200 to-yellow-200 group-hover:from-red-200 group-hover:to-yellow-200 dark:text-white dark:hover:text-gray-900">
					<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
						Red to Yellow
					</span>
				</button>
			</main>

			<Footer />
		</div>
	);
}
