import Head from "next/head";
import Image from "next/image";
import Footer from "@components/Footer";
import Navbar from "@components/Navbar";
import Section from "@components/Section";
import { MoonIcon, SunIcon } from "@heroicons/react/outline";
import { GlobalContext } from "@utils/GlobalContext";
import { useContext } from "react";
import BackToTop from "@components/BackToTop";
import Layout from "@components/Layout";

export default function Learn() {
	const { darkMode, setDarkMode } = useContext(GlobalContext);
	return (
		<div>
			<Head>
				<title>Learn Page</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<Layout>
				<main className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 pb-16">

					<Section id="gradient-text" name="Gradient Text">
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-red-600">
							long text paragraph from Blue to Red
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-teal-400 to-purple-600">
							long text paragraph from Teal to Purple
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-red-400 to-yellow-600">
							long text paragraph from Red to Yellow
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-red-600">
							long text paragraph from Blue to Red
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-purple-500 to-blue-700">
							long text paragraph from Purple to Blue
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500">
							long text paragraph from Pink to Violet
						</h1>
					</Section>

					<Section id="strong-gradient-text" name="Strong Gradient Text">
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4">
							<span className="bg-clip-text text-transparent bg-gradient-to-r from-teal-400 to-purple-600">
								Teal to Purple
							</span>
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4">
							<span className="bg-clip-text text-transparent bg-gradient-to-r from-red-400 to-yellow-600">
								Red to Yellow
							</span>
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4">
							<span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-red-600">
								Blue to Red 
							</span>
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4">
							<span className="bg-clip-text text-transparent bg-gradient-to-r from-purple-500 to-blue-700">
								Purple to Blue
							</span>
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4">
							<span className="bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500">
								Pink to Violet
							</span>
						</h1>
					</Section>

					<Section id="gradient-monochrome" name="Gradient Monochrome">
						<button type="button" className="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Blue</button>
						<button type="button" className="text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Green</button>
						<button type="button" className="text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Cyan</button>
						<button type="button" className="text-white bg-gradient-to-r from-teal-400 via-teal-500 to-teal-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Teal</button>
						<button type="button" className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Lime</button>
						<button type="button" className="text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Red</button>
						<button type="button" className="text-white bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Pink</button>
						<button type="button" className="text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Purple</button>
					</Section>

					<Section id="gradient-dual-tone" name="Gradient Dual Tone">
						<button type="button" className="text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Purple to Blue</button>
						<button type="button" className="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Cyan to Blue</button>
						<button type="button" className="text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Green to Blue</button>
						<button type="button" className="text-white bg-gradient-to-r from-purple-500 to-pink-500 hover:bg-gradient-to-l font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Purple to Pink</button>
						<button type="button" className="text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Pink to Orange</button>
						<button type="button" className="text-gray-900 bg-gradient-to-r from-teal-200 to-lime-200 hover:bg-gradient-to-l font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Teal to Lime</button>
						<button type="button" className="text-gray-900 bg-gradient-to-r from-red-200 to-yellow-200 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Red to Yellow</button>
					</Section>

					<Section id="gradient-outline" name="Gradient Outline">
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Purple to blue
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Cyan to blue
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-green-400 to-blue-600 group-hover:from-green-400 group-hover:to-blue-600 hover:text-white dark:text-white">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Green to blue
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-500 to-pink-500 group-hover:from-purple-500 group-hover:to-pink-500 hover:text-white dark:text-white">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Purple to pink
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-pink-500 to-orange-400 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Pink to orange
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-teal-300 to-lime-300 group-hover:from-teal-300 group-hover:to-lime-300 dark:text-white dark:hover:text-gray-900">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Teal to Lime
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-200 to-yellow-200 group-hover:from-red-200 group-hover:to-yellow-200 dark:text-white dark:hover:text-gray-900">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Red to Yellow
							</span>
						</button>
					</Section>

					<div className="!py-2 px-2 rounded mx-4 bg-opacity-20 dark:bg-opacity-40 bg-gray-100 dark:bg-neutral-800 backdrop-filter backdrop-blur fixed bottom-20 right-3 md:right-10 z-10">
						{darkMode ?
							<button onClick={() => setDarkMode(!darkMode)} aria-label="Change Theme" className="w-8 h-8 p-1 transition-all ease-in duration-300 bg-neutral-800 hover:bg-neutral-700 text-white rounded-full">
								<SunIcon />
							</button>
							:
							<button onClick={() => setDarkMode(!darkMode)} aria-label="Change Theme" className="w-8 h-8 p-1 transition-all ease-in duration-300 bg-gray-100 hover:bg-gray-200 rounded-full">
								<MoonIcon />
							</button>
						}
					</div>

					<BackToTop />

				</main>
			</Layout>

			<Footer />
		</div>
	);
}
