import Head from "next/head";
import Image from "next/image";
import Footer from "@components/Footer";
import Navbar from "@components/Navbar";
import Section from "@components/Section";
import { AcademicCapIcon, MoonIcon, SunIcon } from "@heroicons/react/outline";
import { GlobalContext } from "@utils/GlobalContext";
import { useContext } from "react";
import BackToTop from "@components/BackToTop";
import Layout from "@components/Layout";
import { useState } from "react";
import Link from "next/link";

function TocLink({href, text}) {
	return (
		<span className="block mb-1 font-medium text-blue-500 hover:text-blue-600 transition-all">
			<Link href={href}>{text}</Link>
		</span>
	)
}

export default function Learn() {
	const { darkMode, setDarkMode } = useContext(GlobalContext);
	const [open, setOpen] = useState(false)
	return (
		<div>
			<Head>
				<title>Learn Page</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<Layout>
				<main className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 pb-16">

					<Section id="components" name="Learn TOC">
						<div className="grid sm:grid-cols-2 md:grid-cols-3">
							<div>
								<TocLink href="#icon-background" text="Icon Background" />
								<TocLink href="#icon-shadow" text="Icon Shadow" />
								<TocLink href="#icon-shadow-color" text="Icon Shadow Color" />
								<TocLink href="#icon-border" text="Icon Border" />
							</div>
							<div>
								<TocLink href="#nav-icon-menu-animation" text="Nav Icon Menu Animation" />
								<TocLink href="#gradient-border-colorfull" text="Gradient Border Colorfull" />
								<TocLink href="#gradient-background-colorfull" text="Gradient Background Colorfull" />
								<TocLink href="#gradient-border" text="Gradient Border" />
							</div>
							<div>
								<TocLink href="#gradient-text" text="Gradient Text" />
								<TocLink href="#strong-gradient-text" text="Strong Gradient Text" />
								<TocLink href="#gradient-monochrome" text="Gradient Monochrome" />
								<TocLink href="#gradient-dual-tone" text="Gradient Dual Tone" />
								<TocLink href="#gradient-outline" text="Gradient Outline" />
							</div>
						</div>
					</Section>

					<Section id="icon-background" name="Icon Background">
						<div className="flex flex-wrap gap-2 my-2">
							<div className="flex justify-center items-center rounded-sm bg-blue-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded bg-emerald-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-md bg-red-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-lg bg-violet-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-xl bg-orange-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-2xl bg-teal-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-full bg-pink-500 h-12 w-12">
								<AcademicCapIcon className="w-7 h-7 text-white" />
							</div>
						</div>
						<div className="flex flex-wrap gap-2 my-2">
							<div className="flex justify-center items-center rounded-sm bg-blue-100 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-blue-500" />
							</div>
							<div className="flex justify-center items-center rounded bg-emerald-100 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-emerald-500" />
							</div>
							<div className="flex justify-center items-center rounded-md bg-red-100 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-red-500" />
							</div>
							<div className="flex justify-center items-center rounded-lg bg-violet-100 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-violet-500" />
							</div>
							<div className="flex justify-center items-center rounded-xl bg-orange-100 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-orange-500" />
							</div>
							<div className="flex justify-center items-center rounded-2xl bg-teal-100 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-teal-500" />
							</div>
							<div className="flex justify-center items-center rounded-full bg-pink-100 h-12 w-12">
								<AcademicCapIcon className="w-7 h-7 text-pink-500" />
							</div>
						</div>
						<div className="flex flex-wrap gap-2 my-2">
							<div className="flex justify-center items-center rounded-sm bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded bg-gradient-to-t from-green-400 via-green-500 to-green-600 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-md bg-gradient-to-tr from-red-400 via-red-500 to-red-600 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-lg bg-gradient-to-br from-purple-500 via-purple-600 to-purple-700 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-xl bg-gradient-to-bl from-orange-400 via-orange-500 to-orange-600 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-2xl bg-gradient-to-tl from-teal-400 via-teal-500 to-teal-600 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-full bg-gradient-to-l from-pink-400 via-pink-500 to-pink-600 h-12 w-12">
								<AcademicCapIcon className="w-7 h-7 text-white" />
							</div>
						</div>
						<div className="flex flex-wrap gap-2 my-2">
							<div className="flex justify-center items-center rounded-sm bg-gradient-to-r from-blue-300 to-blue-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded bg-gradient-to-t from-green-300 to-green-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-md bg-gradient-to-tr from-red-300  to-red-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-lg bg-gradient-to-br from-purple-300 to-purple-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-xl bg-gradient-to-bl from-orange-300 to-orange-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-2xl bg-gradient-to-tl from-teal-300 to-teal-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-full bg-gradient-to-l from-pink-300 to-pink-400 h-12 w-12">
								<AcademicCapIcon className="w-7 h-7 text-white" />
							</div>
						</div>
						<div className="flex flex-wrap gap-2 my-2">
							<div className="flex justify-center items-center rounded-sm bg-gradient-to-r from-blue-500 to-green-700 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded bg-gradient-to-t from-green-400 to-red-600 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-md bg-gradient-to-tr from-red-400 to-purple-600 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-lg bg-gradient-to-br from-purple-500 to-orange-700 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-xl bg-gradient-to-bl from-orange-400 to-teal-600 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-2xl bg-gradient-to-tl from-teal-400 to-pink-600 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-full bg-gradient-to-l from-pink-400 to-blue-600 h-12 w-12">
								<AcademicCapIcon className="w-7 h-7 text-white" />
							</div>
						</div>
						<div className="flex flex-wrap gap-2 my-2">
							<div className="flex justify-center items-center rounded-sm bg-gradient-to-r from-blue-400 to-green-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded bg-gradient-to-t from-green-400 to-red-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-md bg-gradient-to-tr from-red-400 to-purple-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-lg bg-gradient-to-br from-purple-400 to-orange-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-xl bg-gradient-to-bl from-orange-400 to-teal-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-2xl bg-gradient-to-tl from-teal-400 to-pink-400 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-full bg-gradient-to-l from-pink-400 to-blue-400 h-12 w-12">
								<AcademicCapIcon className="w-7 h-7 text-white" />
							</div>
						</div>
					</Section>

					<Section id="icon-shadow" name="Icon Shadow">
						<div className="flex flex-wrap gap-4 my-4">
							<div className="flex justify-center items-center rounded-sm bg-blue-500 h-12 w-12 shadow-sm">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded bg-emerald-500 h-12 w-12 shadow">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-md bg-red-500 h-12 w-12 shadow-md">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-lg bg-violet-500 h-12 w-12 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-xl bg-orange-500 h-12 w-12 shadow-xl">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
						</div>
						<div className="flex flex-wrap gap-4 my-4">
							<div className="flex justify-center items-center rounded-sm bg-blue-100 h-12 w-12 shadow-sm">
								<AcademicCapIcon className="w-8 h-8 text-blue-500" />
							</div>
							<div className="flex justify-center items-center rounded bg-emerald-100 h-12 w-12 shadow">
								<AcademicCapIcon className="w-8 h-8 text-emerald-500" />
							</div>
							<div className="flex justify-center items-center rounded-md bg-red-100 h-12 w-12 shadow-md">
								<AcademicCapIcon className="w-8 h-8 text-red-500" />
							</div>
							<div className="flex justify-center items-center rounded-lg bg-violet-100 h-12 w-12 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-violet-500" />
							</div>
							<div className="flex justify-center items-center rounded-xl bg-orange-100 h-12 w-12 shadow-xl">
								<AcademicCapIcon className="w-8 h-8 text-orange-500" />
							</div>
						</div>
					</Section>

					<Section id="icon-shadow-color" name="Icon Shadow Color">
						<div className="flex flex-wrap gap-6 my-6">
							<div className="flex justify-center items-center rounded-sm bg-blue-500 h-12 w-12 shadow-blue-500/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded bg-emerald-500 h-12 w-12 shadow-emerald-500/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-md bg-red-500 h-12 w-12 shadow-red-500/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-lg bg-violet-500 h-12 w-12 shadow-violet-500/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-xl bg-orange-500 h-12 w-12 shadow-orange-500/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-2xl bg-teal-500 h-12 w-12 shadow-teal-500/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
							<div className="flex justify-center items-center rounded-full bg-pink-500 h-12 w-12 shadow-pink-500/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-white" />
							</div>
						</div>
						<div className="flex flex-wrap gap-6 my-6">
							<div className="flex justify-center items-center rounded-sm bg-blue-100 h-12 w-12 shadow-blue-400/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-blue-500" />
							</div>
							<div className="flex justify-center items-center rounded bg-emerald-100 h-12 w-12 shadow-emerald-400/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-emerald-500" />
							</div>
							<div className="flex justify-center items-center rounded-md bg-red-100 h-12 w-12 shadow-red-400/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-red-500" />
							</div>
							<div className="flex justify-center items-center rounded-lg bg-violet-100 h-12 w-12 shadow-violet-400/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-violet-500" />
							</div>
							<div className="flex justify-center items-center rounded-xl bg-orange-100 h-12 w-12 shadow-orange-400/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-orange-500" />
							</div>
							<div className="flex justify-center items-center rounded-2xl bg-teal-100 h-12 w-12 shadow-teal-400/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-teal-500" />
							</div>
							<div className="flex justify-center items-center rounded-full bg-pink-100 h-12 w-12 shadow-pink-400/50 shadow-lg">
								<AcademicCapIcon className="w-8 h-8 text-pink-500" />
							</div>
						</div>
					</Section>

					<Section id="icon-border" name="Icon Border">
						<div className="flex flex-wrap gap-2 my-2">
							<div className="flex justify-center items-center rounded-sm border-2 border-dotted border-blue-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-blue-500" />
							</div>
							<div className="flex justify-center items-center rounded border-2 border-dashed border-emerald-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-emerald-500" />
							</div>
							<div className="flex justify-center items-center rounded-md border-4 border-double border-red-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-red-500" />
							</div>
							<div className="flex justify-center items-center rounded-lg border-2 border-dotted border-violet-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-violet-500" />
							</div>
							<div className="flex justify-center items-center rounded-xl border-2 border-dashed border-orange-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-orange-500" />
							</div>
							<div className="flex justify-center items-center rounded-2xl border-4 border-double border-teal-500 h-12 w-12">
								<AcademicCapIcon className="w-8 h-8 text-teal-500" />
							</div>
							<div className="flex justify-center items-center rounded-full border-2 border-dotted border-pink-500 h-12 w-12">
								<AcademicCapIcon className="w-7 h-7 text-pink-500" />
							</div>
						</div>
						<div className="flex flex-wrap gap-2 my-2">
							<div className="flex items-center justify-center p-0.5 rounded-lg bg-gradient-to-br from-blue-600 to-green-500">
								<div className="p-1.5 bg-white dark:bg-neutral-900 rounded-md">
									<AcademicCapIcon className="w-8 h-8 text-green-600" />
								</div>
							</div>
							<div className="flex items-center justify-center p-0.5 rounded-lg bg-gradient-to-br from-green-600 to-red-500">
								<div className="p-1.5 bg-white dark:bg-neutral-900 rounded-md">
									<AcademicCapIcon className="w-8 h-8 text-red-600" />
								</div>
							</div>
							<div className="flex items-center justify-center p-0.5 rounded-lg bg-gradient-to-br from-red-600 to-violet-500">
								<div className="p-1.5 bg-white dark:bg-neutral-900 rounded-md">
									<AcademicCapIcon className="w-8 h-8 text-violet-600" />
								</div>
							</div>
							<div className="flex items-center justify-center p-0.5 rounded-lg bg-gradient-to-br from-violet-600 to-orange-500">
								<div className="p-1.5 bg-white dark:bg-neutral-900 rounded-md">
									<AcademicCapIcon className="w-8 h-8 text-orange-600" />
								</div>
							</div>
							<div className="flex items-center justify-center p-0.5 rounded-full bg-gradient-to-br from-orange-600 to-cyan-500">
								<div className="p-1.5 bg-white dark:bg-neutral-900 rounded-full">
									<AcademicCapIcon className="w-8 h-8 text-cyan-600" />
								</div>
							</div>
							<div className="flex items-center justify-center p-0.5 rounded-full bg-gradient-to-br from-cyan-600 to-pink-500">
								<div className="p-1.5 bg-white dark:bg-neutral-900 rounded-full">
									<AcademicCapIcon className="w-8 h-8 text-pink-600" />
								</div>
							</div>
							<div className="flex items-center justify-center p-0.5 rounded-full bg-gradient-to-br from-pink-600 to-blue-500">
								<div className="p-1.5 bg-white dark:bg-neutral-900 rounded-full">
									<AcademicCapIcon className="w-8 h-8 text-blue-600" />
								</div>
							</div>
						</div>
					</Section>

					<Section id="nav-icon-menu-animation" name="Nav Icon Menu Animation">
						<button className="w-8 h-8 border dark:border-neutral-700 relative focus:outline-none mx-2 mb-2" onClick={() => setOpen(!open)}>
							<span className="sr-only">Open main menu</span>
							<div className="block w-5 absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
								<span aria-hidden="true" className={`${open ? "rotate-45" : "-translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "opacity-0" : ""} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "-rotate-45" : "translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
							</div>
						</button>
						<button className="w-8 h-8 border dark:border-neutral-700 relative focus:outline-none mx-2 mb-2" onClick={() => setOpen(!open)}>
							<span className="sr-only">Open main menu</span>
							<div className="block w-5 absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
								<span aria-hidden="true" className={`${open ? "-rotate-45" : "-translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "opacity-0" : ""} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "rotate-45" : "translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
							</div>
						</button>
						<br />
						<button className="w-8 h-8 border dark:border-neutral-700 relative focus:outline-none mx-2 mb-2" onClick={() => setOpen(!open)}>
							<span className="sr-only">Open main menu</span>
							<div className="block w-5 absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
								<span aria-hidden="true" className={`${open ? "rotate-45" : "-translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "translate-x-3 opacity-0" : ""} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "-rotate-45" : "translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
							</div>
						</button>
						<button className="w-8 h-8 border dark:border-neutral-700 relative focus:outline-none mx-2 mb-2" onClick={() => setOpen(!open)}>
							<span className="sr-only">Open main menu</span>
							<div className="block w-5 absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
								<span aria-hidden="true" className={`${open ? "-rotate-45" : "-translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "-translate-x-3 opacity-0" : ""} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "rotate-45" : "translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
							</div>
						</button>
						<br />
						<button className="w-8 h-8 border dark:border-neutral-700 relative focus:outline-none mx-2 mb-2" onClick={() => setOpen(!open)}>
							<span className="sr-only">Open main menu</span>
							<div className="block w-5 absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
								<span aria-hidden="true" className={`${open ? "rotate-45" : "-translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "opacity-0" : ""} block absolute h-0.5 w-4 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "-rotate-45" : "translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
							</div>
						</button>
						<button className="w-8 h-8 border dark:border-neutral-700 relative focus:outline-none mx-2 mb-2" onClick={() => setOpen(!open)}>
							<span className="sr-only">Open main menu</span>
							<div className="block w-5 absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
								<span aria-hidden="true" className={`${open ? "-rotate-45" : "-translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "opacity-0" : ""} block absolute h-0.5 w-4 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "rotate-45" : "translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
							</div>
						</button>
						<br />
						<button className="w-8 h-8 border dark:border-neutral-700 relative focus:outline-none mx-2 mb-2" onClick={() => setOpen(!open)}>
							<span className="sr-only">Open main menu</span>
							<div className="block w-5 absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
								<span aria-hidden="true" className={`${open ? "rotate-45" : "-translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "opacity-0" : ""} block absolute h-0.5 w-4 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "-rotate-45 w-5" : "translate-y-1.5 w-3"} block absolute h-0.5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
							</div>
						</button>
						<button className="w-8 h-8 border dark:border-neutral-700 relative focus:outline-none mx-2 mb-2" onClick={() => setOpen(!open)}>
							<span className="sr-only">Open main menu</span>
							<div className="block w-5 absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
								<span aria-hidden="true" className={`${open ? "-rotate-45" : "-translate-y-1.5"} block absolute h-0.5 w-5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "opacity-0" : ""} block absolute h-0.5 w-4 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
								<span aria-hidden="true" className={`${open ? "rotate-45 w-5" : "translate-y-1.5 w-3"} block absolute h-0.5 bg-slate-900 dark:bg-white transform transition duration-500 ease-in-out`}></span>
							</div>
						</button>
					</Section>

					<Section id="gradient-border-colorfull" name="Gradient Border Colorfull">
						<div className="grid sm:grid-cols-2 gap-4">
							<div className="feature-preview border-2 border-dashed border-white dark:border-neutral-900 p-8">
								<div className="max-w-md mx-auto">
									<p className="text-3xl text-center dark:text-white">Content</p>
									<p className="mt-4 text-center lg:text-xs text-purple-500 uppercase font-semibold">Coming soon</p>
								</div>
							</div>
							<div className="feature-preview-b border-2 border-dashed border-white dark:border-neutral-900 p-8">
								<div className="max-w-md mx-auto">
									<p className="text-3xl text-center dark:text-white">Content</p>
									<p className="mt-4 text-center lg:text-xs text-purple-500 uppercase font-semibold">Coming soon</p>
								</div>
							</div>
							<div className="feature-preview-c border-2 border-dashed border-white dark:border-neutral-900 p-8">
								<div className="max-w-md mx-auto">
									<p className="text-3xl text-center dark:text-white">Content</p>
									<p className="mt-4 text-center lg:text-xs text-purple-500 uppercase font-semibold">Coming soon</p>
								</div>
							</div>
							<div className="feature-preview-d border-2 border-dashed border-white dark:border-neutral-900 p-8">
								<div className="max-w-md mx-auto">
									<p className="text-3xl text-center dark:text-white">Content</p>
									<p className="mt-4 text-center lg:text-xs text-purple-500 uppercase font-semibold">Coming soon</p>
								</div>
							</div>
						</div>
					</Section>

					<Section id="gradient-background-colorfull" name="Gradient Background Colorfull">
						<div className="grid sm:grid-cols-2 gap-4">
							<div className="feature-preview-e border-2 border-dashed border-white dark:border-neutral-900 p-8">
								<div className="max-w-md mx-auto">
									<p className="text-3xl text-center dark:text-white">Content</p>
									<p className="mt-4 text-center lg:text-xs text-purple-500 uppercase font-semibold">Coming soon</p>
								</div>
							</div>
							<div className="feature-preview-f border-2 border-dashed border-white dark:border-neutral-900 p-8">
								<div className="max-w-md mx-auto">
									<p className="text-3xl text-center dark:text-white">Content</p>
									<p className="mt-4 text-center lg:text-xs text-purple-500 uppercase font-semibold">Coming soon</p>
								</div>
							</div>
							<div className="feature-preview-g border-2 border-dashed border-white dark:border-neutral-900 p-8">
								<div className="max-w-md mx-auto">
									<p className="text-3xl text-center dark:text-white">Content</p>
									<p className="mt-4 text-center lg:text-xs text-purple-500 uppercase font-semibold">Coming soon</p>
								</div>
							</div>
							<div className="feature-preview-h border-2 border-dashed border-white dark:border-neutral-900 p-8">
								<div className="max-w-md mx-auto">
									<p className="text-3xl text-center dark:text-white">Content</p>
									<p className="mt-4 text-center lg:text-xs text-purple-500 uppercase font-semibold">Coming soon</p>
								</div>
							</div>
						</div>
					</Section>

					<Section id="gradient-border" name="Gradient Border">
						<div className="relative inline-flex items-center justify-center p-0.5 mb-4 overflow-hidden text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-purple-600 to-blue-500">
							<div className="relative px-4 py-2 bg-white dark:bg-neutral-900 rounded-md">
								<h4 className="text-xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-purple-600 to-blue-500">
									gradient border with long text paragraph from Purple to Blue
								</h4>
							</div>
						</div>
						<div className="p-0.5 mb-4 overflow-hidden text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-red-600 to-yellow-500">
							<div className="px-4 py-2 bg-white dark:bg-neutral-900 rounded-md">
								<h4 className="text-xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-red-600 to-yellow-500">
									gradient border with long text paragraph from Red to Yellow
								</h4>
							</div>
						</div>
						<div className="p-0.5 mb-4 inline-flex overflow-hidden text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-pink-600 to-violet-500">
							<div className="px-4 py-2 bg-white dark:bg-neutral-900 rounded-md">
								<h4 className="text-xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-pink-600 to-violet-500">
									gradient border with long text paragraph from Pink to Violet
								</h4>
							</div>
						</div>
						<div className="border-2 border-white dark:border-neutral-900 border-dashed mb-4 inline-flex overflow-hidden text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-teal-600 to-violet-500">
							<div className="px-4 py-2 bg-white dark:bg-neutral-900 rounded-md">
								<h4 className="text-xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-teal-600 to-violet-500">
									gradient border dashed with long text paragraph from Teal to Purple
								</h4>
							</div>
						</div>
						<div className="border-2 border-white dark:border-neutral-900 border-dotted mb-4 inline-flex overflow-hidden text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-blue-600 to-red-500">
							<div className="px-4 py-2 bg-white dark:bg-neutral-900 rounded-md">
								<h4 className="text-xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-red-500">
									gradient border dotted with long text paragraph from Blue to Red
								</h4>
							</div>
						</div>
						<div className="border-[6px] p-0.5 border-white dark:border-neutral-900 border-double mb-4 inline-flex overflow-hidden text-sm font-medium text-gray-900 rounded-lg bg-gradient-to-br from-orange-600 to-teal-500">
							<div className="px-4 py-2 bg-white dark:bg-neutral-900 rounded-md">
								<h4 className="text-xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-orange-600 to-teal-500">
									gradient border double with long text paragraph from Orange to Teal
								</h4>
							</div>
						</div>
					</Section>

					<Section id="gradient-text" name="Gradient Text">
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-red-600">
							long text paragraph from Blue to Red
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-teal-400 to-purple-600">
							long text paragraph from Teal to Purple
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-red-400 to-yellow-600">
							long text paragraph from Red to Yellow
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-red-600">
							long text paragraph from Blue to Red
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-purple-500 to-blue-700">
							long text paragraph from Purple to Blue
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4 pb-2 bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500">
							long text paragraph from Pink to Violet
						</h1>
					</Section>

					<Section id="strong-gradient-text" name="Strong Gradient Text">
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4">
							<span className="bg-clip-text text-transparent bg-gradient-to-r from-teal-400 to-purple-600">
								Teal to Purple
							</span>
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4">
							<span className="bg-clip-text text-transparent bg-gradient-to-r from-red-400 to-yellow-600">
								Red to Yellow
							</span>
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4">
							<span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-red-600">
								Blue to Red
							</span>
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4">
							<span className="bg-clip-text text-transparent bg-gradient-to-r from-purple-500 to-blue-700">
								Purple to Blue
							</span>
						</h1>
						<h1 className="sm:text-5xl text-3xl font-extrabold mb-4">
							<span className="bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500">
								Pink to Violet
							</span>
						</h1>
					</Section>

					<Section id="gradient-monochrome" name="Gradient Monochrome">
						<button type="button" className="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Blue</button>
						<button type="button" className="text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Green</button>
						<button type="button" className="text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Cyan</button>
						<button type="button" className="text-white bg-gradient-to-r from-teal-400 via-teal-500 to-teal-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Teal</button>
						<button type="button" className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Lime</button>
						<button type="button" className="text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Red</button>
						<button type="button" className="text-white bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Pink</button>
						<button type="button" className="text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Purple</button>
					</Section>

					<Section id="gradient-dual-tone" name="Gradient Dual Tone">
						<button type="button" className="text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Purple to Blue</button>
						<button type="button" className="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Cyan to Blue</button>
						<button type="button" className="text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Green to Blue</button>
						<button type="button" className="text-white bg-gradient-to-r from-purple-500 to-pink-500 hover:bg-gradient-to-l font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Purple to Pink</button>
						<button type="button" className="text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Pink to Orange</button>
						<button type="button" className="text-gray-900 bg-gradient-to-r from-teal-200 to-lime-200 hover:bg-gradient-to-l font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Teal to Lime</button>
						<button type="button" className="text-gray-900 bg-gradient-to-r from-red-200 to-yellow-200 hover:bg-gradient-to-bl font-medium rounded-lg text-sm px-4 py-2 text-center mr-2 mb-2">Red to Yellow</button>
					</Section>

					<Section id="gradient-outline" name="Gradient Outline">
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Purple to blue
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Cyan to blue
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-green-400 to-blue-600 group-hover:from-green-400 group-hover:to-blue-600 hover:text-white dark:text-white">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Green to blue
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-500 to-pink-500 group-hover:from-purple-500 group-hover:to-pink-500 hover:text-white dark:text-white">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Purple to pink
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-pink-500 to-orange-400 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Pink to orange
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-teal-300 to-lime-300 group-hover:from-teal-300 group-hover:to-lime-300 dark:text-white dark:hover:text-gray-900">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Teal to Lime
							</span>
						</button>
						<button className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-200 to-yellow-200 group-hover:from-red-200 group-hover:to-yellow-200 dark:text-white dark:hover:text-gray-900">
							<span className="relative px-4 py-2 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
								Red to Yellow
							</span>
						</button>
					</Section>

					<div className="!py-2 px-2 rounded mx-4 bg-opacity-20 dark:bg-opacity-40 bg-gray-100 dark:bg-neutral-800 backdrop-filter backdrop-blur fixed bottom-20 right-3 md:right-10 z-10">
						{darkMode ?
							<button onClick={() => setDarkMode(!darkMode)} aria-label="Change Theme" className="w-8 h-8 p-1 transition-all ease-in duration-300 bg-neutral-800 hover:bg-neutral-700 text-white rounded-full">
								<SunIcon />
							</button>
							:
							<button onClick={() => setDarkMode(!darkMode)} aria-label="Change Theme" className="w-8 h-8 p-1 transition-all ease-in duration-300 bg-gray-100 hover:bg-gray-200 rounded-full">
								<MoonIcon />
							</button>
						}
					</div>

					<BackToTop />

				</main>
			</Layout>

			<Footer />
		</div>
	);
}
