import Navbar from '@components/Navbar';
import Head from 'next/head';

export default function Slider() {
  return (
    <>
      <style jsx>
        {`
          
        `}
      </style>
      <Head>
        <title>Splide.js Page</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-8">
        <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
          Swiper Nav Pagination Scrollbar
        </h1>

      </main>
    </>
  )
}