import Head from "next/head";
import ExLayoutDashboard from "@components/exdashboard/ExLayoutDashboard";

export default function Third() {
  return (
    <>
      <Head>
        <title>Third - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ExLayoutDashboard>
        <div className="bg-orange-500 h-96 flex items-center justify-center">
          <h1 className="text-white font-medium text-2xl px-8">Example Dashboard Layout using Component</h1>
        </div>
        <div className="bg-purple-500 h-96">
        </div>
        <div className="bg-pink-500 h-96">
        </div>
      </ExLayoutDashboard>
    </>
  )
}